name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag (1.x.x)'
        required: true

jobs:
  release-build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install

      - name: Update version
        run: poetry version ${{ inputs.release-tag }}

      - name: Commit and push if changes
        run: |
          changes=$(git diff --name-only origin/master | wc -l)
          if [ $changes -gt 0 ]
          then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add pyproject.toml
            git commit -am "Bump version to ${{ inputs.release-tag }}"
            git tag "v${{ inputs.release-tag }}"
            git push --follow-tags
          fi

      - name: Build release distributions
        run: poetry build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4.1.8
        with:
          name: release-dists
          path: dist/

      - name: Release package
        uses: softprops/action-gh-release@v2.2.1
        with:
          generate_release_notes: true
          name: firefly.py v${{ inputs.release-tag }}
          tag_name: v${{ inputs.release-tag }}
          files: dist/*

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4